pipeline {
    agent any
    tools {
        go 'go 1.11.1'
    }
    environment {
        BUILD = sh (script: 'git rev-list HEAD --count', returnStdout: true).trim()
        GIT_COMMIT = sh (script: 'git rev-parse HEAD', returnStdout: true).trim()
        BRANCH_NAME = sh (script: 'echo ${GIT_BRANCH#origin/} | sed "s/\//_/g"', returnStdout: true).trim()
    }
    stages {
        stage('Checkout') {
            steps {
                echo '从GitHub下载项目源码'
                checkout([$class: 'GitSCM', branches: [[name: 'origin/k8s_test']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'YMhao', url: 'https://github.com/YMhao/demo.git']]])
            }
        }
        stage('构建镜像') {
            steps {
                sh '''
                    echo ${BRANCH_NAME} - ${GIT_COMMIT} - ${BUILD}
                    echo $PWD
                    echo `ls`
                    docker --version
                    cd devops/docker
                    docker build -t nginx:test .
                '''
            }
        }
    }      
}